chore: Setup Testing Environment
atlp-rwanda/orcas-phantom-frontend pull request #1
Opened 2020-09-21 19:33 UTC by maximeish

### What this PR does
Add Jest and Sinon as testing frameworks

### Task to be completed
Modified package.json

### Manual testing
clone github repository then check package.json

### Background context
N/A

### Relevant pivotal tracker stories
https://trello.com/c/DjJg31l0/25-setup-testing-environment

### Screenshots
N/A

2020-09-21 21:47 UTC, julesntare commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Testing Environment](https://trello.com/c/DjJg31l0/25-setup-testing-environment)

2020-09-22 05:34 UTC, IRANKUND reviewed
well done Maxime

2020-09-22 06:37 UTC, giranezafiacre approved these changes
well done

2020-09-22 08:48 UTC, Malaba6 requested changes

2020-09-22 08:48 UTC, Malaba6 commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Plz, add the test scripts here

2020-09-22 09:41 UTC, maximeish commented on package.json
> +    "test": "jest ./src/test/"
@Malaba6 
I added the test for Jest

2020-09-22 09:43 UTC, maximeish commented on package.json
> +    "test": "jest ./src/test/"
@Malaba6 
I thought we are only going to use Jest for testing, do we need Sinon too?

2020-09-22 19:36 UTC, julesntare approved these changes

2020-09-23 07:37 UTC, Malaba6 approved these changes
LGTM

2020-09-23 07:39 UTC, merged

2020-10-04 15:15 UTC, maximeish commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Testing Environment](https://trello.com/c/DjJg31l0/25-setup-testing-environment)