Landing page transition on Open&close
atlp-rwanda/orcas-phantom-frontend pull request #27
Opened 2020-11-19 06:16 UTC by joshwambere

### What this PR does

- Create transition while opening or clossing landing page side menus

### Task to be completed

> - Add transition in open and closing of landing page side menu

### Manual testing

- Clone the github repository

- run npm install

- run npm run dev to start the dev server

### Background context
N/A

### Relevant pivotal tracker stories
https://trello.com/c/Xqzn9Uxz/60-add-css-transition-effects-the-two-side-menu-on-the-home-page
### Screenshots
N/A

2020-11-19 10:10 UTC, maximeish requested changes
![image](https://user-images.githubusercontent.com/54126307/99652173-2b807d00-2a60-11eb-9e9b-7f2e7d2aa136.png)
Good job @joshwambere , the transitions are working fine but can you also try to add some space to the sides of this search panel

2020-11-19 16:54 UTC, maximeish approved these changes

2020-11-20 13:16 UTC, Imaraika approved these changes
Johnson I have reviewed your PR. you implemented all features as expected.! the transition 
 animation is working on Landing page when someone open or close the side menu

2020-11-22 15:40 UTC, Rwandarushya approved these changes

2020-11-22 15:45 UTC, Rwandarushya approved these changes
The transition is working fine @joshwambere

2020-11-23 09:54 UTC, merged